### ISSUE TITLE
Houdini 19

### ISSUE THREAD

**Issue by simonott1** [arqtiq/HouLEAP#4]
I'm trying to use HouLEAP on Houdini 19 (Windows 10) and get this error in the initialize node:
`Traceback (most recent call last):
File "Sop/LEAP_Initialize/init", line 1, in <module>
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
File "C:/Users/ei/Documents/houdini19.0/scripts/python\houleap.py", line 2, in <module>
    import Leap
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\lib\site-packages-forced\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
File "C:/Users/ei/Documents/houdini19.0/scripts/python\Leap.py", line 28, in <module>
    LeapPython = swig_import_helper()
File "C:/Users/ei/Documents/houdini19.0/scripts/python\Leap.py", line 24, in swig_import_helper
    _mod = imp.load_module('LeapPython', fp, pathname, description)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
File "C:\PROGRA~1\SIDEEF~1\HOUDIN~1.383\python37\lib\imp.py", line 342, in load_dynamic
   return _load(spec)
ImportError: DLL load failed: The specified module could not be found.`

Do you have an idea what the issue could be?

Big thank you for this awesome integration!
Best regards, Simon

**Comment by arqtiq** [comment]
Did you copy everything from the HouLEAP/houdini/scripts/python folder ? Looks like it can't find a DLL file

**Comment by noadanimation** [comment]
Have you installed a Python 2 version of Houdini 19? The default is Python 3, that didn’t work for me with Houleap, you have to go in to the download options on Sidefx’s website and choose to show py2 versions

**Comment by arqtiq** [comment]
I haven't thought of python 3 versions, but I checked code and both Leap lib and HouLEAP should handle it. I have tests to do on this

**Comment by simonott1** [comment]
With the Python 2 version of Houdini 19 it does work :)

**Comment by arqtiq** [comment]
I investigated a bit this issue :
- I wrote HouLEAP code to be compatible python 2 or 3, so no problems here
- Leap official python library only supports pyton 2.7 for now

So until Leap releases an updated library that supports python 3.x, we'll have to stick to houdini py2 versions.
I'll add a disclaimer on the readme to avoid further confusions ! Thanks for the report :)

**Comment by simonott1** [comment]
A big thank you for your support :)

**Comment by arqtiq** [comment]
No problem !
Btw I closed the issue but I'm looking into shipping a modified version of the official SDK which supports both versions :)
